export const customFieldValues = [
	"boolean",
	"boolean_digit",
	"buildingNumber",
	"building_number",
	"card_expiration",
	"card_number",
	"card_type",
	"city",
	"company_name",
	"counter",
	"country",
	"countryCode",
	"country_code",
	"date",
	"dateTime",
	"date_time",
	"ean",
	"email",
	"firstName",
	"first_name",
	"image",
	"lastName",
	"last_name",
	"latitude",
	"longText",
	"long_text",
	"longitude",
	"name",
	"null",
	"number",
	"phone",
	"pokemon",
	"postcode",
	"state",
	"streetAddress",
	"streetName",
	"street_address",
	"street_name",
	"text",
	"upc",
	"uuid",
	"vat",
	"website",
	"word",
] as const;

export type CustomFields = Record<string, (typeof customFieldValues)[number]>;
